apiVersion: aws.example.corp/v1alpha1
kind: Instance
metadata:
  name: example
  namespace: default
spec:
  parameters:
    region: us-east-1
    amiId: ami-0005e0cfe09cc9050
    keyPairName: test-key-pair
